
const gymsharkProducts = [
    {
        id: 1,
        name: 'GFX-Crew-Socks-3pk',
        productName: 'GFX Crew Socks',
        image1: '/public/images/3pk1.JPG',
        image2: '/public/images/3pk2.JPG',
        image3: '/public/images/3pk3.JPG',
        image4: '/public/images/3pk4.JPG',
        color: 'White',
        category: 'Body fit',
        size: 'S',
        price: 310
    },
    {
        id: 111,
        name: 'Crew-Socks-7PK',
        productName: 'Crew socks 7pK',
        image1: '/public/images/socks.JPG',
        image2: '/public/images/socks.JPG',
        color: 'White',
        category: 'Body fit',
        size: 'L',
        price: 410
    },
    {
        id: 2,
        name: 'Crew-Socks-5pk',
        productName: 'Crew socks 5pk',
        image1: '/public/images/5pk1.JPG',
        image2: '/public/images/5pk2.JPG',
        color: 'Plum Pink/Deep Teal/Citrus Green/Capri Blue/Grape Purple',
        category: 'Body fit',
        size: 'S',
        price: 250
    },
    {
        id: 3,
        name: 'Adapt-Animal-Seamless-Crop-Tank',
        productName: 'Adapt Animal Seamless Crop Tank',
        image1: '/public/images/cherrybrown1.JPG',
        image2: '/public/images/cherrybrown2.JPG',
        image3: '/public/images/cherrybrown3.JPG',
        image4: '/public/images/cherrybrown4.JPG',
        image5: '/public/images/cherrybrown5.JPG',
        color: 'Reef | Cherry Brown',
        category: 'Body fit',
        size: 'S',
        price: 1400
    },
    {
        id: 4,
        name: 'Sport-Bra',
        productName: 'Crossover Sport Bra',
        image1: '/public/images/greenbra1.JPG',
        image2: '/public/images/greenbra2.JPG',
        image3: '/public/images/greenbra3.JPG',
        image4: '/public/images/greenbra4.JPG',
        image5: '/public/images/greenbra5.JPG',
        image6: '/public/images/greenbra6.JPG',
        color: 'Desert Sage Green',
        category: 'Body fit',
        size: 'S',
        price: 1200
    },
    {
        id: 5,
        name: 'Adapt-Camo-Seamless-Sports-Bra',
        productName: 'Adapt Camo Seamless Sports Bra',
        image1: '/public/images/greybra1.JPG',
        image2: '/public/images/greybra2.JPG',
        image3: '/public/images/greybra3.JPG',
        image4: '/public/images/greybra4.JPG',
        image5: '/public/images/greybra5.JPG',
        image6: '/public/images/greybra6.JPG',
        color: 'Pebble Grey/Soul Brown',
        category: 'Body fit',
        size: 'M',
        price: 1430
    },
    {
        id: 6,
        name: 'Adapt-Camo-Seamless-Lace-Up-Back-Top',
        productName: 'Adapt Camo Seamless Lace Up Back Top',
        image1: '/public/images/redback1.JPG',
        image2: '/public/images/redback2.JPG',
        image3: '/public/images/redback3.JPG',
        image4: '/public/images/redback4.JPG',
        image5: '/public/images/redback5.JPG',
        image6: '/public/images/redback6.JPG',
        color: 'Storm Red/Cherry Brown',
        category: 'Body fit',
        size: 'S',
        price: 1450
    },
    {
        id: 7,
        name: 'Crossover-Sport-Bra',
        productName: 'Crossover Sport Bra',
        image1: '/public/images/lavenderbra1.JPG',
        image2: '/public/images/lavenderbra2.JPG',
        image3: '/public/images/lavenderbra3.JPG',
        image4: '/public/images/lavenderbra4.JPG',
        image5: '/public/images/lavenderbra5.JPG',
        image6: '/public/images/lavenderbra6.JPG',
        color: 'Slate Lavender',
        category: 'Body fit',
        size: 'M | S',
        price: 1200
    },
    {
        id: 8,
        name: 'Elevate-Longline-Sports-Bra',
        productName: 'Elevate Longline Sports Bra',
        image1: '/public/images/olivebra1.JPG',
        image2: '/public/images/olivebra2.JPG',
        image4: '/public/images/olivebra3.JPG',
        image3: '/public/images/olivebra4.JPG',
        image5: '/public/images/olivebra5.JPG',
        image6: '/public/images/olivebra6.JPG',
        color: 'Moss Olive',
        category: 'Body fit',
        size: 'S | M',
        price: 1300
    },
    {
        id: 9,
        name: 'Legacy-Ruched-Tights-Shorts',
        productName: 'Legacy Ruched Tights Shorts',
        image1: '/public/images/bluelegacy1.JPG',
        image2: '/public/images/bluelegacy2.JPG',
        image3: '/public/images/bluelegacy3.JPG',
        image4: '/public/images/bluelegacy4.JPG',
        image5: '/public/images/bluelegacy5.JPG',
        image6: '/public/images/bluelegacy6.JPG',
        color: 'Lakgeside Blue',
        category: 'Body fit',
        size: 'S',
        price: 1320
    },
    {
        id: 10,
        name: 'Pocket-Shorts',
        productName: 'Pocket Shorts',
        image1: '/public/images/pocketblue1.JPG',
        image2: '/public/images/pocketblue2.JPG',
        image3: '/public/images/pocketblue3.JPG',
        image4: '/public/images/pocketblue4.JPG',
        image5: '/public/images/pocketblue5.JPG',
        image6: '/public/images/pocketblue6.JPG',
        color: 'Denim Blue',
        category: 'Body fit',
        size: 'M',
        price: 1290
    },
    {
        name: 'Studio-Shorts',
        productName: 'Studio Shorts',
        image1: '/public/images/studioblack1.jpg',
        image2: '/public/images/studioblack2.jpg',
        image3: '/public/images/studioblack3.jpg',
        image4: '/public/images/studioblack4.jpg',
        image5: '/public/images/studioblack5.jpg',
        image6: '/public/images/studioblack6.jpg',
        color: 'Black',
        category: 'Body fit',
        size: 'S',
        price: 1500
    },
    {
        id: 12,
        name: 'Gs-Power-Original-Leggings',
        productName: 'Gs Power Original Leggingss',
        image1: '/public/images/powerblue1.JPG',
        image2: '/public/images/powerblue2.JPG',
        image3: '/public/images/powerblue3.JPG',
        image4: '/public/images/powerblue4.JPG',
        image5: '/public/images/powerblue5.JPG',
        image6: '/public/images/powerblue6.JPG',
        color: 'Coastal Blue',
        category: 'Body fit',
        size: 'S',
        price: 1650
    },
    {
        id: 13,
        name: 'Adapt-Animal-Seamless-Leggings',
        productName: 'Adapt Animal Seamless Leggins',
        image1: '/public/images/legingblack1.JPG',
        image2: '/public/images/legingblack2.JPG',
        image3: '/public/images/legingblack3.JPG',
        image4: '/public/images/legingblack4.JPG',
        image5: '/public/images/legingblack6.JPG',
        image6: '/public/images/legingblack7.JPG',
        color: 'Reef | Black',
        category: 'Body fit',
        size: 'S',
        price: 1690
    },
    {
        id: 14,
        name: 'Flex-High-Waisted-Leggings',
        productName: 'Flex High Waisted Leggings',
        image1: '/public/images/marlegins4.jpg',
        image2: '/public/images/marlegins5.jpg',
        image3: '/public/images/marlegins6.jpg',
        color: 'Earl Blue Marl',
        category: 'Body fit',
        size: 'S',
        price: 1800
    },
    {
        id: 15,
        name: 'Legacy-Sports-Bra',
        productName: 'Legacy Sports Bra',
        image1: '/public/images/hoyabra1.JPG',
        image2: '/public/images/hoyabra2.JPG',
        image3: '/public/images/hoyabra3.JPG',
        image4: '/public/images/hoyabra4.JPG',
        image5: '/public/images/hoyabra5.JPG',
        image6: '/public/images/hoyabra6.JPG',
        color: 'Hoya Green',
        category: 'Body fit',
        size: 'S',
        price: 1300
    },
    {
        id: 16,
        name: 'Vital-Seamless-2.0-High-Neck-Midi_top',
        productName: 'Vital Seamless 2.0 High Neck Midi top',
        image1: '/public/images/midtopblack1.JPG',
        image2: '/public/images/midtopblack2.JPG',
        image3: '/public/images/midtopblack3.JPG',
        color: 'Black Marl',
        category: 'Body fit',
        size: 'M',
        price: 1500
    },
    {
        id: 17,
        name: 'Vital-Seamless-2.0-High-Neck-Midi-top',
        productName: 'Vital Seamless 2.0 High Neck Midi top',
        image1: '/public/images/midtopblue1.JPG',
        image2: '/public/images/midtopblue2.JPG',
        image3: '/public/images/midtopblue3.JPG',
        image4: '/public/images/midtopblue4.JPG',
        image5: '/public/images/midtopblue5.JPG',
        image6: '/public/images/midtopblue6.JPG',
        color: 'Stellar Blue Marl',
        category: 'Body fit',
        size: 'S',
        price: 1500
    }
]

export default gymsharkProducts;
