
const gymsharkProducts = [
    {
        id: 1,
        name: 'GFX-Crew-Socks-3pk',
        productName: 'GFX Crew Socks',
        image1: '../../src/images/gymsharkImages/3pk1.JPG',
        image2: '../../src/images/gymsharkImages/3pk2.JPG',
        image3: '../../src/images/gymsharkImages/3pk3.JPG',
        image4: '../../src/images/gymsharkImages/3pk4.JPG',
        color: 'White',
        category: 'Body fit',
        size: 'S',
        price: 18.00
    },
    {
        id: 111,
        name: 'Crew-Socks-7PK',
        productName: 'Crew socks 7pK',
        image1: '../../src/images/gymsharkImages/socks.JPG',
        image2: '../../src/images/gymsharkImages/socks.JPG',
        color: 'White',
        category: 'Body fit',
        size: 'L',
        price: 40.00
    },
    {
        id: 2,
        name: 'Crew-Socks-5pk',
        productName: 'Crew socks 5pk',
        image1: '../../src/images/gymsharkImages/5pk1.JPG',
        image2: '../../src/images/gymsharkImages/5pk2.JPG',
        color: 'Plum Pink/Deep Teal/Citrus Green/Capri Blue/Grape Purple',
        category: 'Body fit',
        size: 'S',
        price: 24.00
    },
    {
        id: 3,
        name: 'Adapt-Animal-Seamless-Crop-Tank',
        productName: 'Adapt Animal Seamless Crop Tank',
        image1: '../../src/images/gymsharkImages/cherrybrown1.JPG',
        image2: '../../src/images/gymsharkImages/cherrybrown2.JPG',
        image3: '../../src/images/gymsharkImages/cherrybrown3.JPG',
        image4: '../../src/images/gymsharkImages/cherrybrown4.JPG',
        image5: '../../src/images/gymsharkImages/cherrybrown5.JPG',
        color: 'Reef | Cherry Brown',
        category: 'Body fit',
        size: 'S',
        price: 28.00
    },
    {
        id: 4,
        name: 'Sport-Bra',
        productName: 'Crossover Sport Bra',
        image1: '../../src/images/gymsharkImages/greenbra1.JPG',
        image2: '../../src/images/gymsharkImages/greenbra2.JPG',
        image3: '../../src/images/gymsharkImages/greenbra3.JPG',
        image4: '../../src/images/gymsharkImages/greenbra4.JPG',
        image5: '../../src/images/gymsharkImages/greenbra5.JPG',
        image6: '../../src/images/gymsharkImages/greenbra6.JPG',
        color: 'Desert Sage Green',
        category: 'Body fit',
        size: 'S',
        price: 18.00
    },
    {
        id: 5,
        name: 'Adapt-Camo-Seamless-Sports-Bra',
        productName: 'Adapt Camo Seamless Sports Bra',
        image1: '../../src/images/gymsharkImages/greybra1.JPG',
        image2: '../../src/images/gymsharkImages/greybra2.JPG',
        image3: '../../src/images/gymsharkImages/greybra3.JPG',
        image4: '../../src/images/gymsharkImages/greybra4.JPG',
        image5: '../../src/images/gymsharkImages/greybra5.JPG',
        image6: '../../src/images/gymsharkImages/greybra6.JPG',
        color: 'Pebble Grey/Soul Brown',
        category: 'Body fit',
        size: 'M',
        price: 18.40
    },
    {
        id: 6,
        name: 'Adapt-Camo-Seamless-Lace-Up-Back-Top',
        productName: 'Adapt Camo Seamless Lace Up Back Top',
        image1: '../../src/images/gymsharkImages/redback1.JPG',
        image2: '../../src/images/gymsharkImages/redback2.JPG',
        image3: '../../src/images/gymsharkImages/redback3.JPG',
        image4: '../../src/images/gymsharkImages/redback4.JPG',
        image5: '../../src/images/gymsharkImages/redback5.JPG',
        image6: '../../src/images/gymsharkImages/redback6.JPG',
        color: 'Storm Red/Cherry Brown',
        category: 'Body fit',
        size: 'S',
        price: 18.40
    },
    {
        id: 7,
        name: 'Crossover-Sport-Bra',
        productName: 'Crossover Sport Bra',
        image1: '../../src/images/gymsharkImages/lavenderbra1.JPG',
        image2: '../../src/images/gymsharkImages/lavenderbra2.JPG',
        image3: '../../src/images/gymsharkImages/lavenderbra3.JPG',
        image4: '../../src/images/gymsharkImages/lavenderbra4.JPG',
        image5: '../../src/images/gymsharkImages/lavenderbra5.JPG',
        image6: '../../src/images/gymsharkImages/lavenderbra6.JPG',
        color: 'Slate Lavender',
        category: 'Body fit',
        size: 'M | S',
        price: 25.50
    },
    {
        id: 8,
        name: 'Elevate-Longline-Sports-Bra',
        productName: 'Elevate Longline Sports Bra',
        image1: '../../src/images/gymsharkImages/olivebra1.JPG',
        image2: '../../src/images/gymsharkImages/olivebra2.JPG',
        image4: '../../src/images/gymsharkImages/olivebra3.JPG',
        image3: '../../src/images/gymsharkImages/olivebra4.JPG',
        image5: '../../src/images/gymsharkImages/olivebra5.JPG',
        image6: '../../src/images/gymsharkImages/olivebra6.JPG',
        color: 'Moss Olive',
        category: 'Body fit',
        size: 'S | M',
        price: 26.40
    },
    {
        id: 9,
        name: 'Legacy-Ruched-Tights-Shorts',
        productName: 'Legacy Ruched Tights Shorts',
        image1: '../../src/images/gymsharkImages/bluelegacy1.JPG',
        image2: '../../src/images/gymsharkImages/bluelegacy2.JPG',
        image3: '../../src/images/gymsharkImages/bluelegacy3.JPG',
        image4: '../../src/images/gymsharkImages/bluelegacy4.JPG',
        image5: '../../src/images/gymsharkImages/bluelegacy5.JPG',
        image6: '../../src/images/gymsharkImages/bluelegacy6.JPG',
        color: 'Lakgeside Blue',
        category: 'Body fit',
        size: 'S',
        price: 24.00
    },
    {
        id: 10,
        name: 'Pocket-Shorts',
        productName: 'Pocket Shorts',
        image1: '../../src/images/gymsharkImages/pocketblue1.JPG',
        image2: '../../src/images/gymsharkImages/pocketblue2.JPG',
        image3: '../../src/images/gymsharkImages/pocketblue3.JPG',
        image4: '../../src/images/gymsharkImages/pocketblue4.JPG',
        image5: '../../src/images/gymsharkImages/pocketblue5.JPG',
        image6: '../../src/images/gymsharkImages/pocketblue6.JPG',
        color: 'Denim Blue',
        category: 'Body fit',
        size: 'M',
        price: 28.00
    },
    {
        id: 11,
        name: 'Studio-Shorts',
        productName: 'Studio Shorts',
        image1: '../../src/images/gymsharkImages/studioblack1.jpg',
        image2: '../../src/images/gymsharkImages/studioblack2.jpg',
        image3: '../../src/images/gymsharkImages/studioblack3.jpg',
        image4: '../../src/images/gymsharkImages/studioblack4.jpg',
        image5: '../../src/images/gymsharkImages/studioblack5.jpg',
        image6: '../../src/images/gymsharkImages/studioblack6.jpg',
        color: 'Black',
        category: 'Body fit',
        size: 'S',
        price: 36.00
    },
    {
        id: 12,
        name: 'Gs-Power-Original-Leggings',
        productName: 'Gs Power Original Leggingss',
        image1: '../../src/images/gymsharkImages/powerblue1.JPG',
        image2: '../../src/images/gymsharkImages/powerblue2.JPG',
        image3: '../../src/images/gymsharkImages/powerblue3.JPG',
        image4: '../../src/images/gymsharkImages/powerblue4.JPG',
        image5: '../../src/images/gymsharkImages/powerblue5.JPG',
        image6: '../../src/images/gymsharkImages/powerblue6.JPG',
        color: 'Coastal Blue',
        category: 'Body fit',
        size: 'S',
        price: 22.40
    },
    {
        id: 13,
        name: 'Adapt-Animal-Seamless-Leggings',
        productName: 'Adapt Animal Seamless Leggins',
        image1: '../../src/images/gymsharkImages/legingblack1.JPG',
        image2: '../../src/images/gymsharkImages/legingblack2.JPG',
        image3: '../../src/images/gymsharkImages/legingblack3.JPG',
        image4: '../../src/images/gymsharkImages/legingblack4.JPG',
        image5: '../../src/images/gymsharkImages/legingblack6.JPG',
        image6: '../../src/images/gymsharkImages/legingblack7.JPG',
        color: 'Reef | Black',
        category: 'Body fit',
        size: 'S',
        price: 38.40
    },
    {
        id: 14,
        name: 'Flex-High-Waisted-Leggings',
        productName: 'Flex High Waisted Leggings',
        image1: '../../src/images/gymsharkImages/marlegins4.jpg',
        image2: '../../src/images/gymsharkImages/marlegins5.jpg',
        image3: '../../src/images/gymsharkImages/marlegins6.jpg',
        color: 'Earl Blue Marl',
        category: 'Body fit',
        size: 'S',
        price: 25.00
    },
    {
        id: 15,
        name: 'Legacy-Sports-Bra',
        productName: 'Legacy Sports Bra',
        image1: '../../src/images/gymsharkImages/hoyabra1.JPG',
        image2: '../../src/images/gymsharkImages/hoyabra2.JPG',
        image3: '../../src/images/gymsharkImages/hoyabra3.JPG',
        image4: '../../src/images/gymsharkImages/hoyabra4.JPG',
        image5: '../../src/images/gymsharkImages/hoyabra5.JPG',
        image6: '../../src/images/gymsharkImages/hoyabra6.JPG',
        color: 'Hoya Green',
        category: 'Body fit',
        size: 'S',
        price: 26.60
    },
    {
        id: 16,
        name: 'Vital-Seamless-2.0-High-Neck-Midi_top',
        productName: 'Vital Seamless 2.0 High Neck Midi top',
        image1: '../../src/images/gymsharkImages/midtopblack1.JPG',
        image2: '../../src/images/gymsharkImages/midtopblack2.JPG',
        image3: '../../src/images/gymsharkImages/midtopblack3.JPG',
        color: 'Black Marl',category: 'Body fit',
        size: 'M',
        price: 64.40
    },
    {
        id: 17,
        name: 'Vital-Seamless-2.0-High-Neck-Midi-top',
        productName: 'Vital Seamless 2.0 High Neck Midi top',
        image1: '../../src/images/gymsharkImages/midtopblue1.JPG',
        image2: '../../src/images/gymsharkImages/midtopblue2.JPG',
        image3: '../../src/images/gymsharkImages/midtopblue3.JPG',
        image4: '../../src/images/gymsharkImages/midtopblue4.JPG',
        image5: '../../src/images/gymsharkImages/midtopblue5.JPG',
        image6: '../../src/images/gymsharkImages/midtopblue6.JPG',
        color: 'Stellar Blue Marl',
        category: 'Body fit',
        size: 'S',
        price: 55.20
    },

    
]

export default gymsharkProducts