const wproducts = [
    {
        id: 1,
        name: 'Falda-Deportiva-Basic-tenis',
        productName: 'Falda Deportiva Básica De Tenis',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/faldatenis1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/faldatenis2.jpg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/faldatenis3.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/faldatenis4.jpg?raw=true',
        color: 'Negro',
        category: 'Body fit',
        size: 'S | M',
        price: 490,
        stock: 'Agotado',
    },
    {
        id: 2,
        name: 'Gym-Sport-Bra',
        productName: 'Gym Sport Bra',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra3.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra2.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra5.JPG?raw=true',
        color: 'Negro, Beige Blanco',
        category: 'Body fit',
        size: 'S',
        price: 360,
        stock: 'Color negro agotado',
    },
    {
        id: 3,
        name: 'Gym-Shorts',
        productName: 'Gym shorts',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymshort1.jpg?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymshort2.jpg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymshort3.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymshort4.JPG?raw=true',
        color: 'Negro, Morado Claro, Morado Oscuro',
        category: 'Body fit',
        size: 'S | M',
        price: 395
    },
    {
        id: 4,
        name: 'Gym-Shorts-Highs',
        productName: 'Gym Shorts Highs',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/shorthigh1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/shorthigh2.JPG?raw=true',
        color: 'Negro, Gris, Beige, Celeste Claro',
        category: 'Body fit',
        size: 'S',
        price: 395
    },
    {
        id: 5,
        name: 'Biker-Shorts',
        productName: 'Biker Shorts',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort2.jpg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort3.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort4.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort5.JPG?raw=true',
        color: 'Negro, Gris Claro, Rosado, Gris Oscuro',
        category: 'Body fit',
        size: 's',
        price: 430,
        stock: 'Color negro agotado',
    },
    {
        id: 6,
        name: 'Seamless-Crop-Top',
        productName: 'Seamless Crop Top',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/croptop1.jpg?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/croptop2.jpg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/croptop3.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/croptop4.jpg?raw=true',
        color: 'Negro, Morado, Rosado, Gris',
        category: 'Body fit',
        size: 'S',
        price: 380,
        stock: 'Color negro y rosado agotado',
    }
];

export default wproducts;
