const wproducts = [
    {
        id: 1,
        name: 'Power-Seamless-Cycling-Shorts',
        productName: 'Power Seamless Cycling Shorts',
        image1: '../../src/images/wommensBest/Archivo_000.png',
        image2: '../../src/images/wommensBest/Archivo_001.png',
        image3: '../../src/images/wommensBest/Archivo_003.png',
        image4: '../../src/images/wommensBest/Archivo_004.png',
        image5: '../../src/images/wommensBest/Archivo_005.png',
        color: 'Royal Blue',
        category: 'Body fit',
        size: 'S',
        price: 1390
    },
    {
        id: 2,
        name: 'Power-Seamless-Sports-Bra',
        productName: 'Power Seamless Sports Bra',
        image1: '../../src/images/wommensBest/Archivo_006.png',
        image2: '../../src/images/wommensBest/Archivo_007.png',
        image3: '../../src/images/wommensBest/Archivo_008.png',
        image4: '../../src/images/wommensBest/Archivo_009.png',
        image5: '../../src/images/wommensBest/Archivo_010.png',
        image6: '../../src/images/wommensBest/Archivo_011.png',
        color: 'Royal Blue',
        category: 'Body fit',
        size: 'S',
        price: 1200
    },
    {
        id: 3,
        name: 'Power-Seamless-Sports-Bra-Black',
        productName: 'Power Seamless Sports Bra',
        image1: '../../src/images/wommensBest/Archivo_012.png',
        image2: '../../src/images/wommensBest/Archivo_013.png',
        image3: '../../src/images/wommensBest/Archivo_014.png',
        image4: '../../src/images/wommensBest/Archivo_015.png',
        image5: '../../src/images/wommensBest/Archivo_016.png',
        image6: '../../src/images/wommensBest/Archivo_017.png',
        color: 'Black',
        category: 'Body fit',
        size: 'S | M',
        price: 1200
    },
    {
        id: 4,
        name: 'Power-Seamless-Leggings-Black',
        productName: 'Power Seamless Leggings',
        image1: '../../src/images/wommensBest/Archivo_018.png',
        image2: '../../src/images/wommensBest/Archivo_019.png',
        image3: '../../src/images/wommensBest/Archivo_020.png',
        image4: '../../src/images/wommensBest/Archivo_021.png',
        image5: '../../src/images/wommensBest/Archivo_022.png',
        image6: '../../src/images/wommensBest/Archivo_023.png',
        color: 'Black',
        category: 'Body fit',
        size: 'S | M',
        price: 1500
    },
    {
        id: 6,
        name: 'Power-Seamless-Leggings-Royal-Blue',
        productName: 'Power Seamless Leggings',
        image1: '../../src/images/wommensBest/Archivo_024.png',
        image2: '../../src/images/wommensBest/Archivo_025.png',
        image3: '../../src/images/wommensBest/Archivo_026.png',
        image4: '../../src/images/wommensBest/Archivo_027.png',
        image5: '../../src/images/wommensBest/Archivo_028.png',
        color: 'Royal Blue',
        category: 'Body fit',
        size: 'S',
        price: 1500
    },
    {
        id: 7,
        name: 'Power-Seamless-Leggings-Graphite',
        productName: 'Power Seamless Leggings',
        image1: '../../src/images/wommensBest/Archivo_029.png',
        image2: '../../src/images/wommensBest/Archivo_030.png',
        image3: '../../src/images/wommensBest/Archivo_031.png',
        image4: '../../src/images/wommensBest/Archivo_032.png',
        image5: '../../src/images/wommensBest/Archivo_033.png',
        image6: '../../src/images/wommensBest/Archivo_034.png',
        color: 'Graphite',
        category: 'Body fit',
        size: 'M',
        price: 1500
    },
    {
        id: 8,
        name: 'Power-Seamless-Long-Sleeve-Crop-Top',
        productName: 'Power Seamless Long Sleeve Crop Top',
        image1: '../../src/images/wommensBest/Archivo_041.png',
        image2: '../../src/images/wommensBest/Archivo_042.png',
        image3: '../../src/images/wommensBest/Archivo_044.png',
        image4: '../../src/images/wommensBest/Archivo_044.png',
        image5: '../../src/images/wommensBest/Archivo_046.png',
        color: 'Graphite',
        category: 'Body fit',
        size: 'S',
        price: 1350
    },
    {
        id: 9,
        name: 'Power-Seamless-Cycling-Shorts-Graphite',
        productName: 'Power Seamless Cycling Shorts',
        image1: '../../src/images/wommensBest/Archivo_047.png',
        image2: '../../src/images/wommensBest/Archivo_048.png',
        image3: '../../src/images/wommensBest/Archivo_049.png',
        image4: '../../src/images/wommensBest/Archivo_050.png',
        image5: '../../src/images/wommensBest/Archivo_051.png',
        image6: '../../src/images/wommensBest/Archivo_052.png',
        category: 'Body fit',
        size: 'S',
        price: 1390
    },
    {
        id: 10,
        name: 'Power-Seamless-Short-Sleeve-Crop-Top-Dark-Cherry',
        productName: 'Power Seamless Short Sleeve Crop Top',
        image1: '../../src/images/wommensBest/Archivo_053.png',
        image2: '../../src/images/wommensBest/Archivo_054.png',
        image3: '../../src/images/wommensBest/Archivo_055.png',
        image4: '../../src/images/wommensBest/Archivo_056.png',
        image5: '../../src/images/wommensBest/Archivo_058.png',
        color: 'Dark Cherry',
        category: 'Body fit',
        size: 'S',
        price: 1290
    },
    {
        id: 11,
        name: 'Power-Seamless-Cycling-Shorts-Dark-Cherry',
        productName: 'Power Seamless Cycling Shorts',
        image1: '../../src/images/wommensBest/Archivo_059.png',
        image2: '../../src/images/wommensBest/Archivo_060.png',
        image3: '../../src/images/wommensBest/Archivo_061.png',
        image4: '../../src/images/wommensBest/Archivo_062.png',
        image5: '../../src/images/wommensBest/Archivo_063.png',
        image6: '../../src/images/wommensBest/Archivo_064.png',
        color: 'Dark Cherry',
        category: 'Body fit',
        size: 'S',
        price: 1390
    },
    {
        id: 12,
        name: 'Power-Seamless-Long-Sleeve-Crop-Top-Walnut-Brown',
        productName: 'Power Seamless Long Sleeve Crop',
        image1: '../../src/images/wommensBest/Archivo_065.png',
        image2: '../../src/images/wommensBest/Archivo_066.png',
        image3: '../../src/images/wommensBest/Archivo_067.png',
        image4: '../../src/images/wommensBest/Archivo_068.png',
        image5: '../../src/images/wommensBest/Archivo_069.png',
        image6: '../../src/images/wommensBest/Archivo_070.png',
        color: 'Walnut Brown',
        category: 'Body fit',
        size: 'S',
        price: 1350
    },
    {
        id: 13,
        name: 'Power-Seamless-Cycling-Shorts-Walnut-Brown',
        productName: 'Power Seamless Cycling Shorts',
        image1: '../../src/images/wommensBest/Archivo_071.png',
        image2: '../../src/images/wommensBest/Archivo_072.png',
        image3: '../../src/images/wommensBest/Archivo_073.png',
        image4: '../../src/images/wommensBest/Archivo_074.png',
        image5: '../../src/images/wommensBest/Archivo_075.png',
        image6: '../../src/images/wommensBest/Archivo_076.png',
        color: 'Walnut Brown',
        category: 'Body fit',
        size: 'S',
        price: 1390
    }
];

export default wproducts